name: Bring Up Environment

on:
  workflow_dispatch:

jobs:
  deploy-infra:
    uses: ./.github/workflows/deploy-infra.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write

  deploy-app:
    needs: deploy-infra
    uses: ./.github/workflows/deploy-app.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write
